name: survey_app
version: 1.0.0+1
publish_to: none
description: Municipal Survey Application
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  get: 4.6.1
  google_fonts: ^2.3.1
  hexcolor: ^2.0.4
  image_picker: ^0.8.5
  image_cropper: ^1.5.1
  flutter_image_compress: ^1.1.0
  geocoding: ^2.0.4
  geolocator: ^8.2.0
  permission_handler: ^9.2.0
  get_storage: ^2.0.3
  intl: ^0.17.0
  print_bluetooth_thermal: ^1.0.5
  esc_pos_utils_plus: ^2.0.1+6
  datetime_picker_formfield: ^2.0.0
  month_year_picker: ^0.2.0+2

  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
